spring:
    profiles:
        active: ${SPRING_PROFILES_ACTIVE}
server:
    port: ${SERVER_PORT}
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}