spring:
    application:
        name: service-discovery
    profiles:
        active: ${ACTIVE_PROFILE}
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
management:
    endpoints:
        web:
            exposure:
                include: health, info, refresh, env
            base-path: /actuator
    endpoint:
        health:
            show-details: always
app:
    security:
        user:
            name: ${SECURE_USER_NAME}
            password: ${SECURE_USER_PASSWORD}